# Generated by Django 3.2.12 on 2023-10-07 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_caption_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Excerpt',
            new_name='excerpt',
        ),
    ]
